name: 'Shepherd''s Life, LLC'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/83d6dd05-3a4e-4dca-8115-9a9bd1d3a64e.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/08ba59ae-3f3d-40e1-80a4-52e62ecfdcea.jpg
layout_spectrum: 0.0912632500696886
typography_spectrum: 0.6098891932858477
opengraph:
  type: ''
  appId: '173538179336025'
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/652f6341-d6fa-47bc-9875-2173476a2f97.jpg
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.5733479630633798
  lightness: 0.8434476096778896
  saturation: 0.8837146725517991
  rhythmicContrast: 0.7541449829558886
purpose:
  - type: contact
    label: Email us
    url: 'mailto:shepherdslifellc@yahoo.com'
  - type: contact
    label: Contact Us
    url: 'tel:2516560717'
title: shepherd's life
description: bookkeeping and taxes
author:
  name: 'shepherd''s Life '
  url: shepherdslifellc.com
  email: shepherdslifellc@yahoo.com
content_rating:
  adult: false
content: []
github: true
